professions = [
    {
        'name': 'Farmer',
        'minimum_town': 0,
        'natural-resource': True,
        'requires': ['farming'],
        'resource_production': [],
    },
    {
        'name': 'Hunter',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['hunting'],
        'resource_production': [],
    },
    {
        'name': 'Fisherman',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['fishing'],
        'resource_production': [],
    },
    {
        'name': 'Lumberjack',
        'minimum_town': 0, 
        'natural_resource': True,
        'requires': ['woodcutting'],
        'resource_production': [],
    },
    {
        'name': 'Forager',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['foraging'],
        'resource_production': [],
    },
    {
        'name': 'Miner',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['mining'],
        'resource_production': [],
    },
    {
        'name': 'Butcher', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Livestock'],
        'resource_production': ['Meats'],
    },
    {
        'name': 'Fishmonger', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Fish'],
        'resource_production': [],
    },
    {
        'name': 'Carpenter', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Lumber'],
        'resource_production': [],
    },
]