professions = [
    {
        'name': 'Baker', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Flour'],
        'input_capacity': 10,
        'resource_production': ['Food'],
        'export_multiplier': 1,
        'tag': 'Food',
        'work_building': 'bakery',
        'input_count': 0,
    },
    {
        'name': 'Miller', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Grain'],
        'input_capacity': 20,
        'resource_production': ['Flour'],
        'export_multiplier': 2,
        'tag': 'Food',
        'work_building': 'mill',
        'input_count': 0,
    },
        {
        'name': 'Butcher', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Livestock'],
        'input_capacity': 20,
        'resource_production': ['Meats', 'Hide'],
        'export_multiplier': 2,
        'tag': 'Food',
        'work_building': 'butcher shop',
        'input_count': 0,
    },
    {
        'name': 'Fishmonger', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Fish'],
        'input_capacity': 5,
        'resource_production': ['Food'],
        'export_multiplier': 2,
        'tag': 'Food',
        'work_building': 'fish stall',
        'input_count': 0,
    },
    {
        'name': 'Carpenter', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Lumber'],
        'input_capacity': 10,
        'resource_production': [],
        'tag': 'Essential',
        'work_building': 'carpenter shop',
        'input_count': 0,
    },
    {
        'name': 'Refiner', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Iron Ore'],
        'input_capacity': 20,
        'resource_production': ['Smelted Iron'],
        'export_multiplier': 1,
        'tag': '',
        'work_building': 'refinery',
        'input_count': 0,
    },
        {
        'name': 'Blacksmith', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Smelted Iron'],
        'input_capacity': 10,
        'resource_production': ['Weapons', 'Armor', 'Tools'],
        'export_multiplier': 1,
        'tag': 'Essential',
        'work_building': 'blacksmith',
        'input_count': 0,
    },
        {
        'name': 'Tanner', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Hide'],
        'input_capacity': 20,
        'resource_production': ['Leather'],
        'export_multiplier': 1,
        'tag': '',
        'work_building': 'tannery',
        'input_count': 0,
    },
    {
        'name': 'Cobbler', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Leather'],
        'input_capacity': 10,
        'resource_production': ['Shoes'],
        'export_multiplier': 1,
        'tag': 'Commodity',
        'work_building': 'cobbler',
        'input_count': 0,
    },
    {
        'name': 'Furrier', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Furs'],
        'input_capacity': 10,
        'resource_production': ['Clothes'],
        'export_multiplier': 1,
        'tag': 'Commodity',
        'work_building': 'haberdashery',
        'input_count': 0,
    },
    {
        'name': 'Leatherworker', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Leather'],
        'input_capacity': 10,
        'resource_production': ['Clothes'],
        'export_multiplier': 1,
        'tag': 'Commodity',
        'work_building': 'haberdashery',
        'input_count': 0,
    },
    {
        'name': 'Clothier', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Cotton'],
        'input_capacity': 10,
        'resource_production': ['Clothes'],
        'export_multiplier': 1,
        'tag': 'Commodity',
        'work_building': 'haberdashery',
        'input_count': 0,
    },
    {
        'name': 'Farmer',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['farming'],
        'input_capacity': 1,
        'resource_production': ['Livestock', 'Grain', 'Cotton'],
        'export_multiplier': 1,
        'tag': 'Food',
        'work_building': 'farmstead',
        'input_count': 0,
    },
    {
        'name': 'Hunter',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['hunting'],
        'input_capacity': 1,
        'resource_production': ['Furs', 'Meats'],
        'export_multiplier': 2,
        'tag': 'Food',
        'work_building': 'hunting lodge',
        'input_count': 0,
    },
    {
        'name': 'Fisherman',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['fishing'],
        'input_capacity': 1,
        'resource_production': ['Fish'],
        'export_multiplier': 1,
        'tag': 'Food',
        'work_building': 'boat',
        'input_count': 0,   
    },
    {
        'name': 'Lumberjack',
        'minimum_town': 0, 
        'natural_resource': True,
        'requires': ['woodcutting'],
        'input_capacity': 1,
        'resource_production': ['Lumber'],
        'export_multiplier': 1,
        'tag': '',
        'work_building': None,
        'input_count': 0,
    },
    {
        'name': 'Forager',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['foraging'],
        'input_capacity': 1,
        'resource_production': ['Herbs', 'Food'],
        'export_multiplier': 2,
        'tag': 'Food',
        'work_building': None,
        'input_count': 0,
    },
    {
        'name': 'Miner',
        'minimum_town': 0,
        'natural_resource': True,
        'requires': ['mining'],
        'input_capacity': 1,
        'resource_production': ['Iron Ore', 'Gold Ore', 'Stone', 'Marble'],
        'export_multiplier': 1,
        'tag': '',
        'work_building': 'mine',
        'input_count': 0,
    },
    {
        'name': 'Innkeeper', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': ['Alcohol'],
        'input_capacity': 20,
        'resource_production': [],
        'tag': 'Entertainment',
        'work_building': 'tavern',
        'input_count': 0,
    },
    {
        'name': 'Unemployed', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': [],
        'resource_production': [],
        'tag': 'Unemployed',
        'work_building': 'the street',
        'input_count': 0,
    },
    {
        'name': 'Shopkeep', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': [],
        'resource_production': [],
        'tag': 'Essential',
        'work_building': 'general store',
        'input_count': 0,
    },
    {
        'name': 'Midwife', 
        'minimum_town': 0, 
        'natural_resource': False,
        'requires': [],
        'resource_production': [],
        'tag': 'Essential',
        'work_building': 'various homes',
        'input_count': 0,
    },
]